name: Fouth workflow demo
on: [workflow _dispatch, push]
jobs:
  show infot:
    runs-on: Ubuntu-latest
    steps: 
        - name: Output Infor
          run: echo"${{ toJSON(github) }}"
    