name: Fouth workflow demo
on: 
  workflow _dispatch:
  pull_request:
    types: [opened, synchronize]
jobs:
  show-info:
    runs-on: ubuntu-latest
    steps: 
        - name: Output Info
          run: echo"${{ toJSON(github) }}"
    